# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_thirdWindow(object):

    def setupUi(self, thirdWindow):
        thirdWindow.setObjectName("MainWindow")
        thirdWindow.resize(800, 341)
        self.centralwidget = QtWidgets.QWidget(thirdWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result_2 = QtWidgets.QLabel(self.centralwidget)
        self.result_2.setGeometry(QtCore.QRect(83, 220, 611, 71))
        font = QtGui.QFont()
        font.setFamily("타이포_쌍문동 B")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.result_2.setFont(font)
        self.result_2.setStyleSheet("")
        self.result_2.setAlignment(QtCore.Qt.AlignCenter)
        self.result_2.setObjectName("result_2")
        self.result_3 = QtWidgets.QLabel(self.centralwidget)
        self.result_3.setGeometry(QtCore.QRect(63, 380, 251, 101))
        font = QtGui.QFont()
        font.setFamily("타이포_쌍문동 B")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.result_3.setFont(font)
        self.result_3.setText("")
        self.result_3.setAlignment(QtCore.Qt.AlignCenter)
        self.result_3.setObjectName("result_3")
        self.result_4 = QtWidgets.QLabel(self.centralwidget)
        self.result_4.setGeometry(QtCore.QRect(90, 260, 611, 71))
        font = QtGui.QFont()
        font.setFamily("타이포_쌍문동 B")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.result_4.setFont(font)
        self.result_4.setStyleSheet("")
        self.result_4.setAlignment(QtCore.Qt.AlignCenter)
        self.result_4.setObjectName("result_4")
        thirdWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(thirdWindow)
        QtCore.QMetaObject.connectSlotsByName(thirdWindow)

    def retranslateUi(self, thirdWindow):
        _translate = QtCore.QCoreApplication.translate
        thirdWindow.setWindowTitle(_translate("thirdWindow", "thirdWindow"))
        self.result_2.setText(_translate("thirdWindow", "주문이 완료되었습니다!!"))
        self.result_4.setText(_translate("thirdWindow", "이용해주셔서 감사합니다~"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    thirdWindow = QtWidgets.QMainWindow()
    ui = Ui_thirdWindow()
    ui.setupUi(thirdWindow)
    thirdWindow.show()
    sys.exit( )
